README.md

Hi there,
renamed the path of the source to the module registry instead of the GitHub repo
removed variables because all variable information is sourced from the variable and output files.
If you can merge this into master and then add another release/tag so that the module registry will update. After that we'll be able to verify this module.
Thanks
Chris

Reformatting README for Terraform Registry

---

modules/mysql/main.tf
modules/mysql/variables.tf
modules/postgresql/main.tf
modules/postgresql/variables.tf
test/fixtures/mysql-ha/main.tf
test/fixtures/postgresql-ha/main.tf

To support multiple databases, this commit adds the `additional_databases` argument in both modules. This doesn't break the backward compatibility.
@danisla @morgante

enable mutltiple databases

---

modules/mysql/README.md
modules/mysql/main.tf
modules/mysql/variables.tf
modules/postgresql/README.md
modules/postgresql/main.tf
modules/postgresql/variables.tf
test/fixtures/mysql-ha/main.tf
test/fixtures/postgresql-ha/main.tf
test/integration/mysql-ha/controls/mysql.rb
test/integration/postgresql-ha/controls/pg.rb

This PR is last part of our upgrading process for the module.
To avoid breaking backward compatibility, I dropped [a commit](https://github.com/GoogleCloudPlatform/terraform-google-sql-db/pull/21/commits/de16a90bcde43968ab888850a72f4962fa40232e) in #21, but I think it's time to merge this changes for our improvement as we discussed before in internal.
@danisla @morgante

enable multiple users

---

CONTRIBUTING.md

Lints all the terraform in the repo and fixes if needed. Perhaps I should change check_terraform to validate_terraform?
The second commit is after everything is applied.

Updates the hcl linting

---

modules/mysql/README.md
modules/mysql/failover_replica.tf
modules/mysql/read_replica.tf
modules/mysql/variables.tf
modules/postgresql/README.md
modules/postgresql/read_replica.tf
modules/postgresql/variables.tf
modules/private_service_access/README.md
modules/safer_mysql/README.md
modules/safer_mysql/main.tf
modules/safer_mysql/variables.tf
test/fixtures/mysql-ha/main.tf
test/fixtures/postgresql-ha/main.tf
test/integration/mysql-ha/controls/mysql.rb
test/integration/postgresql-ha/controls/pg.rb

To do this, this commit allows you to set the suffix for replicas.
Fixes #44
@morgante @aaron-lane  @wadefrancis could you take a look?

avoid name conflicts when replicas recreation

---

modules/postgresql/main.tf
modules/postgresql/outputs.tf
modules/postgresql/variables.tf

I am trying to use the `postgresql` submodule with the `private_service_access` submodule that was created as part of #35 for MySQL (really appreciate that work!). There's nothing in `private_service_access` that's MySQL specific, but the `peering_completed` variable workaround to enforce dependency order was only added to `safer_mysql`.
I also added a [`private_address` output](https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#private_ip_address) to `postgresql`, trying to mirror the preexisting `instance_address` output. The README for the project says this works with a 1.12.x version of the google provider, but `private_ip_address` wasn't introduced until version [version 2.1.0](https://github.com/terraform-providers/terraform-provider-google/blob/master/CHANGE …

Postgres support for private_service_access

---

README.md

This commit updates the README to include the human-readable names and the programmatic names of the required roles and APIs. It also corrects the name of the base required API from Cloud SQL to Cloud SQL Admin.

Clarify required roles, APIs

---

CHANGELOG.md
modules/private_service_access/main.tf

This commit adds a network data source to the private_service_access
submodule and uses that data source to obtain the required network
attributes.
This change fixes the following issue:
> Error: Provider produced inconsistent final plan
>
> When expanding the plan for
> module.private-service-access.google_service_networking_connection.private_service_access
> to include new values learned so far during apply, provider "google-beta"
> produced an invalid new value for .network: was
> cty.StringVal("test-vpc-private-access"), but now
> cty.StringVal("https://www.googleapis.com/compute/v1/projects/test-project/global/networks/test-vpc-private-access").
>
> This is a bug in the provider, which should be reported in the provider's own
> issue tracker.
Related to …

Use self link in service networking connection

---

CHANGELOG.md
examples/mysql-and-postgres-private/main.tf
modules/mysql/README.md
modules/mysql/main.tf
modules/mysql/variables.tf
modules/postgresql/README.md
modules/postgresql/main.tf
modules/postgresql/variables.tf
modules/safer_mysql/README.md
modules/safer_mysql/main.tf
modules/safer_mysql/variables.tf
test/fixtures/safer-mysql-simple/main.tf

Replace extraneous label with module dependency.

---

examples/mysql-ha/main.tf
examples/mysql-private/main.tf
examples/mysql-public/main.tf
examples/postgresql-ha/main.tf
examples/postgresql-public/main.tf
modules/mysql/variables.tf
modules/mysql/versions.tf
modules/postgresql/variables.tf
modules/postgresql/versions.tf
modules/private_service_access/versions.tf
modules/safer_mysql/variables.tf

Updating google and google-beta provider constraints to `~> 3.5`

Updating google and google-beta providers

---

README.md

cause this is not enough to use this module from the public registry
```
module "sql-db" {
source  = "GoogleCloudPlatform/sql-db/google"
version = "3.1.0"
}
```
This warn help us, but can be more explicit :
This module version (3.1.0) has no root configuration. A module with no root configuration cannot be used directly.
Use the submodules dropdown above to view the 4 submodules defined within this module.
So add a small usage guideline in the readme and examples with remote usage can help us

complete provision instructions

---

examples/mysql-ha/main.tf
modules/mysql/README.md
modules/mysql/main.tf
modules/mysql/variables.tf
test/integration/mysql-ha/controls/mysql.rb

Closes https://github.com/terraform-google-modules/terraform-google-sql-db/issues/71
https://cloud.google.com/sql/docs/mysql/high-availability#HA-configuration
>The HA configuration, sometimes called a cluster, provides data redundancy. A Cloud SQL instance configured for HA is also called a regional instance and is located in a primary and secondary zone within the configured region. Within a regional instance, the configuration is made up of a primary instance (master) and a standby instance. Through synchronous replication to each zone's persistent disk, all writes made to the primary instance are also made to the standby instance. In the event of an instance or zone failure, this configuration reduces downtime, and your data continues to be available to client applications.
>Note: The …

Support new regional HA MySQL

---

modules/safer_mysql/README.md
modules/safer_mysql/main.tf
modules/safer_mysql/variables.tf

I notice that the support for availability_type is recently merged for mysql, but not added for safer_mysql.

add availability_type support for safer_mysql

---

examples/postgresql-ha/main.tf
modules/postgresql/main.tf
modules/postgresql/variables.tf

This removes `backup_configuration.binary_log_enabled` as an option in the postgres module, as attempting to set it as true results in an error:
```
Error: Error, failed to create instance <instance-name>: googleapi: Error 400: Invalid request: Binary log can only be enabled for MySQL instances., invalid
on .terraform/modules/terraform-google-sql/modules/postgresql/main.tf line 26, in resource "google_sql_database_instance" "default":
26: resource "google_sql_database_instance" "default" {
```

Hardcode disable option as it is not valid for postgres

---

examples/mysql-ha/main.tf
examples/mysql-private/main.tf
examples/postgresql-ha/main.tf
modules/mysql/main.tf
modules/mysql/variables.tf
modules/postgresql/main.tf
modules/postgresql/variables.tf
modules/safer_mysql/variables.tf

^
Closes #96
Noticed a couple of object fields `instance` and` project` were never used so also removed them
To consider
- Merge `users` and `additonal_users`  + same for databases, seems a bit pointless having them seperate and since we've already done a breaking API change might as well merge them now.
- Move read_replicas to `for_each`

Move users/databases to for_each

---

modules/mssql/README.md
modules/mssql/main.tf
modules/mssql/variables.tf
modules/mysql/README.md
modules/mysql/main.tf
modules/mysql/variables.tf
modules/postgresql/README.md
modules/postgresql/main.tf
modules/postgresql/variables.tf
modules/safer_mysql/README.md
modules/safer_mysql/main.tf
modules/safer_mysql/variables.tf

There is an issue if you would like to create a DB with the same name. With the current approach, you need to change the name every time or you have to work around and use something like `random_id`
> **If I delete my instance, can I reuse the instance name?**
> Yes, but not right away. The instance name is unavailable for up to a week before it can be reused.
More information is here [Managing Your Instances](https://cloud.google.com/sql/faq?hl=en#managing-your-instances)

Added: random_id for mysql instance name

---

modules/mssql/versions.tf

Ran into Provider dependency issues with other modules in the same project that required a newer Provider version

Relax Provider version

---

modules/mysql/README.md
modules/mysql/variables.tf
modules/postgresql/README.md
modules/postgresql/variables.tf

Resolve #107 comment and add reference for mysql.

Update links for database flags on postgresql and mysql

---

examples/mssql-public/main.tf
modules/mssql/README.md
modules/mssql/main.tf
modules/mssql/variables.tf
modules/mssql/versions.tf

This PR fixes #130 
Google-beta provider version updated because the encryption_key_name feature was implemented in [3.9.0](https://github.com/hashicorp/terraform-provider-google-beta/blob/master/CHANGELOG.md#390-february-18-2020)

Add encryption_key_name variable for MS SQL module

---

docs/upgrading_to_sql_db_4.0.0.md
modules/mysql/read_replica.tf
modules/postgresql/read_replica.tf

Fix replica state key

---

README.md
modules/safer_mysql/README.md

Hi !
First, thanks for your work.
I added a mssql example in the README and I corrected a typo.
I looked at your safer_mysql. Do you know if a safer_postgresql  is possible and if it's possible, are you interessed for a PR about this ?
Thanks !

Add mssql example in README and typo

---

modules/mssql/README.md
modules/mssql/main.tf
modules/mssql/variables.tf
modules/mysql/README.md
modules/mysql/main.tf
modules/mysql/variables.tf
modules/postgresql/README.md
modules/postgresql/main.tf
modules/postgresql/variables.tf

Now with https://github.com/hashicorp/terraform-provider-google/pull/7557 deletion_protection is set to `true` by default on `google_sql_database_instance`.
This PR add this attributes to modules.
I don't know what to do with safer_mysql module ?

feat(attributes): add deletion_protection boolean

---

modules/mysql/README.md
modules/mysql/main.tf
modules/mysql/variables.tf
modules/postgresql/README.md
modules/postgresql/main.tf
modules/postgresql/variables.tf

This PR cleans up previous changes in the expected structure of the zone variable. 
This [commit](https://github.com/terraform-google-modules/terraform-google-sql-db/commit/5e1ae20e5b7efdbb35f733897f5a4378389337d3) changed the expected form of the zone variable but didn't change it in all uses of the variable and didn't update documentation.

Zone structure fixes

---

modules/postgresql/README.md
modules/postgresql/main.tf
modules/postgresql/variables.tf

Hello,
I'd like to add the option to enable or disable the creation of the default database and user.
At the moment if I delete the default DB from the google console, terraform recreate it at the next run.

Add variable for managing the creation of the default database and user

---

examples/mysql-ha/versions.tf
examples/mysql-private/versions.tf
examples/mysql-public/versions.tf
examples/postgresql-ha/versions.tf
examples/postgresql-public/versions.tf
modules/mysql/versions.tf
modules/postgresql/versions.tf
modules/private_service_access/versions.tf
modules/safer_mysql/versions.tf
test/fixtures/mysql-ha/versions.tf
test/fixtures/mysql-private/versions.tf
test/fixtures/mysql-public/versions.tf
test/fixtures/postgresql-ha/versions.tf
test/fixtures/postgresql-public/versions.tf
test/setup/versions.tf

This PR adds support for terraform 0.14.
Note: it is considered a "best practice" to not define upper limits for terraform core version in reusable modules:
> # Terraform Core and Provider Versions
> Reusable modules should constrain *only their minimum allowed versions of Terraform* and providers, such as >= 0.12.0. This helps avoid known incompatibilities, while allowing the user of the module flexibility to upgrade to newer versions of Terraform without altering the module.
See https://www.terraform.io/docs/configuration/version-constraints.html#terraform-core-and-provider-versions

Support terraform 0.14+

---

modules/mysql/README.md
modules/mysql/main.tf
modules/mysql/variables.tf

Hello,
I'd like to add the option to enable or disable the creation of the default database and user. (mysql)
At the moment if I delete the default DB from the google console, terraform recreate it at the next run.

Add variable for managing the creation of the default database and user (mysql)

---

kitchen.yml
modules/postgresql/README.md
modules/postgresql/variables.tf
test/integration/mssql-ha/controls/mssql.rb
test/integration/mssql-ha/inspec.yml
test/integration/mssql-public/controls/mssql.rb
test/integration/mssql-public/inspec.yml
test/integration/mysql-ha/controls/mysql.rb
test/integration/mysql-ha/inspec.yml
test/integration/mysql-private/controls/mysql.rb
test/integration/mysql-private/controls/peering.rb
test/integration/mysql-private/inspec.yml
test/integration/mysql-public/controls/mysql.rb
test/integration/mysql-public/inspec.yml
test/integration/postgresql-ha/controls/pg.rb
test/integration/postgresql-ha/inspec.yml
test/integration/postgresql-public/controls/pg.rb
test/integration/postgresql-public/inspec.yml

gcp-inpsec for Cloud SQL has deprecated a set of attributes in v.1.8.0 (issue documented [here](https://github.com/inspec/inspec-gcp/issues/321)) causing integration tests to fail. This PR updates all 6 integration test to use gcloud instead for gcp-inspec.
Additionally, there's a minor changes for increasing the timeout for postgresql operations to 15m since provisioning was failing on 10m.

fix: deprecates the usage of gcp-inspec and replaces integration tests with gcloud

---

examples/postgresql-public-iam/README.md
examples/postgresql-public-iam/main.tf
examples/postgresql-public-iam/outputs.tf
examples/postgresql-public-iam/variables.tf
examples/postgresql-public-iam/versions.tf
kitchen.yml
modules/postgresql/README.md
modules/postgresql/main.tf
modules/postgresql/variables.tf
test/fixtures/postgresql-public-iam/main.tf
test/fixtures/postgresql-public-iam/outputs.tf
test/fixtures/postgresql-public-iam/variables.tf
test/fixtures/postgresql-public-iam/versions.tf
test/integration/postgresql-public-iam/controls/pg.rb
test/integration/postgresql-public-iam/inspec.yml
test/setup/iam.tf
test/setup/main.tf

The postgresql module has been extended to accept IAM users (both Google IDs and Service Accounts) as valid users to the database. In addition to that, this PR contains an example for provisioning IAM users and a corresponding integration test.

feat: extended the postgresql module to accept IAM users and services accounts

---

modules/postgresql/main.tf

This is a fix for the issue referenced [here](https://github.com/terraform-google-modules/terraform-google-sql-db/issues/222). The cause was due to terraform interpreting `null` as a literal value instead of using the default value. It seems to have been an issue for awhile and is referenced in this [terraform thread](https://github.com/hashicorp/terraform/issues/21702).

Postgres additional_users: prevent null from being passed as password

---

examples/mssql-public/main.tf
examples/mysql-ha/main.tf
examples/mysql-private/main.tf
examples/mysql-public/main.tf
examples/postgresql-ha/main.tf
examples/postgresql-public-iam/main.tf
examples/postgresql-public/main.tf
modules/mysql/versions.tf
modules/postgresql/versions.tf
modules/private_service_access/versions.tf
test/setup/main.tf

https://github.com/terraform-google-modules/terraform-google-sql-db/issues/227
- Update `hashicorp/null` and `hashicorp/random` providers to `3.1.0` to keep up with providers updates.
- Remove provider constraints from fixtures since providers versions are pinned with `required_provider`

Update null and random providers

---

modules/postgresql/read_replica.tf

GCP now has option to enable Query Insights also for replica instances and this PR will enable it to set this via terraform

Adding option to enable insights for replica instances

---

modules/mssql/main.tf

root_password can only be set by the provider when
the instance is provisioned and it seems that even if
the provider could read the password then one would not
wish to destroy and recreate the instance because the
password did not match what was in Terraform.
This is specifically relevant to emergency maintenance
where somebody might have to re-import a cloned version
of the SQL server into state in a cleanup exercise. The
imported server has a null root_password because that is
what the provider has to set it to on import. The password
currently present in the state in this scenario will force
a destroy and create of the instance because of this
change.
The way to avoid this is to ignore changes for root_password

Ignore changes to root_password

---

modules/mysql/versions.tf
modules/postgresql/versions.tf

You are using the google-beta provider in `main.tf`, but it's not declared in the `required_providers` block, which creates a warning on each run.

Add missing google-beta provider to required_providers

---

modules/private_service_access/README.md
modules/private_service_access/main.tf
modules/private_service_access/variables.tf

To allow importing existing resources into the module as missing description forces a replacement.

Add a description variable for google_compute_global_address resource

---

modules/mssql/README.md
modules/mssql/main.tf
modules/mssql/variables.tf
modules/mssql/versions.tf

This change beings support for connecting SQL servers to Managed AD domain.
New feature available in [v4.22.0 provider](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#domain)

feat!: add support for settings.active_directory_config for SQL module

---

modules/mysql/outputs.tf

running terraform plan on MySQL module was generating errors
because the values in these outputs are considered sensitive.

fix: Add sensitive flag for MySQL module outputs

---

examples/mssql-public/README.md
examples/mssql-public/main.tf
examples/mssql-public/variables.tf
modules/mssql/README.md
modules/mssql/main.tf
modules/mssql/variables.tf
test/fixtures/mssql-public/main.tf

This change converts the sql_server_audit_config from `map(string)` to `list(map(string))` where for_each was being iterated on each of the map items in `sql_server_audit_config` map. Also updated the example to test `sql_server_audit_config` variable.

fix for_each issue on the sql_audit_config

---

test/fixtures/mssql-ha/main.tf
test/fixtures/mssql-public/main.tf

Now that [this](https://github.com/hashicorp/terraform-provider-google/issues/11891) issue is fixed, we can remove the pinned version for the provider in the test fixtures.

chore:removing pinned version for mssql test fixtures

---

modules/mysql/versions.tf
modules/postgresql/versions.tf
modules/private_service_access/versions.tf

Null provider was originally (https://github.com/terraform-google-modules/terraform-google-sql-db/blob/v12.1.0/modules/postgresql/versions.tf#L22) pessimistic pinned to a particular major.minor.patch, this reverts to just that major.minor for wider version compatibility.
Fixes #371

fix: revert null provider version to major.minor

---

modules/backup/README.md
modules/backup/main.tf
modules/backup/variables.tf

The current setup sets an unique name for sql_instance for the backup jobs. However, it is possible that an user might want more than one backup job - for instance, a weekly, a monthly and a yearly.
The current setup does not allow having diff jobs with different retentions otherwise.

Add Suffix to backup configurations

---

modules/safer_mysql/README.md
modules/safer_mysql/main.tf
modules/safer_mysql/variables.tf
modules/safer_mysql/versions.tf

Partially addresses https://github.com/terraform-google-modules/terraform-google-sql-db/issues/326.
`secondary_zone` was added in TPG [4.28.0](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4280-july-11-2022), as mentioned [here](https://github.com/terraform-google-modules/terraform-google-sql-db/pull/339/files#r989316573), hence the provider bump.

feat: add `secondary_zone`, `follow_gae_application` to safer_mysql

---

modules/safer_mysql/outputs.tf

Hi!
I just simply added the `sensitive = true` parameter to the safer-mysql module as well

feat: :sparkles: sensitive output safer mysql

---

examples/postgresql-public-iam/main.tf
modules/mysql/README.md
modules/mysql/main.tf
modules/mysql/variables.tf
modules/postgresql/README.md
modules/postgresql/main.tf
modules/postgresql/variables.tf

We did not explicitly call this out in the upgrade guide nor provide migration instructions. So adding a flag to retain backward compat.
https://github.com/terraform-google-modules/terraform-google-sql-db/issues/418

fix: make special chars opt in for generated passwords

---

examples/mysql-private/README.md
examples/mysql-private/main.tf
examples/mysql-private/variables.tf
modules/mysql/README.md
modules/mysql/main.tf
modules/mysql/metadata.yaml
modules/mysql/outputs.tf
modules/mysql/variables.tf
modules/safer_mysql/README.md
modules/safer_mysql/main.tf
modules/safer_mysql/variables.tf
test/fixtures/mysql-private/main.tf
test/fixtures/mysql-private/variables.tf
test/integration/mysql-private/mysql_private_test.go
test/setup/main.tf
test/setup/outputs.tf

Fixes #463. Adds `iam_users` variable to add service accounts and IAM users to a CloudSQL database running MySQL.

fix: port iam_users from postgresql module

---

modules/mssql/README.md
modules/mssql/main.tf
modules/mssql/variables.tf

This is the same change being submitted through https://github.com/terraform-google-modules/terraform-google-sql-db/pull/479, submitting a new PR to address the linter check failures on the other PR.
cc @Anand-chenepalli

feat: add time_zone for mssql

---

modules/mssql/README.md
modules/mssql/metadata.yaml
modules/mssql/variables.tf
modules/mysql/README.md
modules/mysql/metadata.yaml
modules/mysql/variables.tf
modules/postgresql/README.md
modules/postgresql/metadata.yaml
modules/postgresql/variables.tf
modules/safer_mysql/README.md
modules/safer_mysql/metadata.yaml
modules/safer_mysql/variables.tf

fix: Cloud SQL does not support multiple deny_maintenance_period block. Update variable description

---

modules/postgresql/versions.tf

Fixes https://github.com/terraform-google-modules/terraform-google-sql-db/issues/552

fix: bump required google provider to 5.6 for postgres

---

modules/mysql/outputs.tf
modules/postgresql/outputs.tf

It should fix error for server ca cert coming from this change on google provider 5.12 and later: https://github.com/hashicorp/terraform-provider-google/pull/16932

fix: mark replicas_instance_server_ca_certs output as sensitive

---

modules/postgresql/README.md
modules/postgresql/main.tf
modules/postgresql/metadata.yaml
modules/postgresql/variables.tf
modules/postgresql/versions.tf

This PR makes below changes,
1. Add `enable_google_ml_integration` setting for database instance. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#enable_google_ml_integration
2. Configurable project roles for default database service account. The default database service account is created for each database instance. To enable database to call ML functions from VertexAI etc, the service account needs suitable project roles. 
This feature has been used in "Gen AI rag with cloud sql" https://github.com/GoogleCloudPlatform/terraform-genai-rag/blob/main/database.tf#L32

feat!: Add enable_google_ml_integration setting for database instance and configurable project roles for default database service account

---

modules/backup/main.tf

IAM conditions can only be used to restrict access to DatabaseInstances or BackupRuns. They can't be used to restrict access to Database resources.
The export workflow uses the `googleapis.sqladmin.v1.databases.list` call to gather all database names.
This call fails with the error code 403: unauthorized when the IAM conditions are set.
> The client is not authorized to make this request.
*Supported Resource Type Values in IAM Conditions: [docs](https://cloud.google.com/iam/docs/conditions-resource-attributes#resource-type)*

fix: Backup - set IAM conditions conditionally

---

modules/backup/main.tf

This commit reverts the change to using the cloudsql.editor role
for the backup service account from the cloudsql.admin role. This was
introduced in https://github.com/terraform-google-modules/terraform-google-sql-db/pull/597 but due to this the deletion of old backups on the
instance now receives a 403 error in the workflow. This is due to the
fact that the cloudsql.editor role lacks the cloudsql.backupRuns.delete
permission.
Closes: https://github.com/terraform-google-modules/terraform-google-sql-db/issues/617

fix!: Cleanup of old instance backups. Change role roles/cloudsql.editor to roles/cloudsql.admin

---

examples/mssql-failover-replica/main.tf
examples/mysql-backup-create-service-account/main.tf
examples/mysql-ha/main.tf
examples/mysql-private/main.tf
examples/mysql-psc/main.tf
examples/mysql-public/main.tf
examples/postgresql-backup-provided-service-account/main.tf
examples/postgresql-ha/main.tf
examples/postgresql-psc/main.tf
examples/postgresql-public-iam/main.tf
examples/postgresql-public/main.tf
examples/postgresql-with-cross-region-failover/main.tf
examples/private_service_access/README.md
examples/private_service_access/main.tf
examples/private_service_access/outputs.tf
examples/private_service_access/variables.tf
modules/private_service_access/README.md
modules/private_service_access/main.tf
modules/private_service_access/variables.tf
modules/private_service_access/versions.tf
test/integration/mssql-failover-replica/mssql_failover_replica_test.go
test/integration/mysql-psc/mysql_psc_test.go
test/integration/postgresql-psc/postgresql_psc_test.go
test/integration/postgresql-with-cross-region-failover/postgresql_cross_region_failover_test.go
test/setup/main.tf

Fix #585 
- Add deletion_policy to private service access sub-module
- Moved private service access sub-module to GA provider (TPG >=5.33)
- Fixed tests: Reduce number of cpu/memory to avoid running out of quota
- Fixed workflow service agent error in test

feat(TPG>5.38)!: added deletion_policy to private service access sub-module and promoted to GA provider

---

modules/postgresql/main.tf
test/integration/postgresql-backup-provided-service-account/postgresql_backup_provided_service_account_test.go
test/integration/postgresql-ha/postgresql_ha_test.go
test/integration/postgresql-psc/postgresql_psc_test.go
test/integration/postgresql-public-iam/postgresql_public_iam_test.go
test/integration/postgresql-public/postgresql_public_test.go

This PR addresses https://github.com/terraform-google-modules/terraform-google-sql-db/issues/624. 
Creation of addition_databases without default database doesn't create an issue of invalid index.
```
module "postgresql" {
source  = "../terraform-google-sql-db/modules/postgresql"
project_id = "<PROJECT_ID>"
name = "database-instance"
database_version = "POSTGRES_14"
enable_default_db = false
additional_databases = [{ name = "any_db_1", charset = "UTF8", collation = "en_US.UTF8" }]
}
```
Note: The PR also disables defaultVerify for postgresql test as it is flaky. No changes in this PR has any impact on the test.

bug: fix invalid index with additional database and default database disabled

---

metadata.display.yaml
modules/backup/metadata.display.yaml
modules/mssql/metadata.display.yaml
modules/mysql/metadata.display.yaml
modules/postgresql/metadata.display.yaml
modules/private_service_access/metadata.display.yaml
modules/restore/metadata.display.yaml
modules/safer_mysql/metadata.display.yaml

Generate medadata.display.yaml file.

chore: Generate metadata.display.yaml 

---

docs/upgrading_to_sql_db_23.0.md
modules/backup/main.tf

My GCP SQL Server exports stopped working a few days ago. The workflow fails with a missing permission `storage.objects.delete` on the Cloud SQL service account. After an exchange with the GCP support, they confirmed internal changes has been made and required new permissions for the Cloud SQL service account onto the bucket:
> After thoroughly reviewing your issue and analyzing similar cases with the tools at my disposal, I can confirm that there have been internal changes to the export method due to ongoing improvements in Google Cloud Storage. Our internal team is diligently addressing this matter to enhance the overall user experience.
> 
> In the meantime, as a workaround while our team investigates, we recommend granting storage.objects.delete permissions to the service account on …

fix!: Change export service account permission for external backups - roles/storage.objectAdmin

---

modules/mysql/metadata.display.yaml
modules/mysql/metadata.yaml
modules/mysql/variables.tf
modules/postgresql/metadata.display.yaml
modules/postgresql/metadata.yaml
modules/postgresql/variables.tf

This PR also updates order of variables for `mysql` and `postgresql` modules.

chore: update display metadata and alternate default of deletion_protection for ADC

---

modules/safer_mysql/README.md
modules/safer_mysql/main.tf
modules/safer_mysql/variables.tf

Those variables are currently not supported by the module `safer_mysql`, but by the module `mysql` which is used under the hood.
This PR adds both variables and hands them over to the module `mysql`.

feat: Add variables "enable_default_db", "enable_default_user" to module "safer_mysql"

---

modules/mysql/metadata.yaml
modules/postgresql/metadata.yaml

This PR adds connection metadata for Postgresql and Mysql modules.

chore: add connection metadata for GCE instance_template

---

examples/postgresql-ha/README.md
examples/postgresql-ha/main.tf
examples/postgresql-ha/outputs.tf
examples/postgresql-ha/variables.tf
modules/postgresql/README.md
modules/postgresql/main.tf
modules/postgresql/variables.tf
test/fixtures/postgresql-ha/main.tf
test/fixtures/postgresql-ha/variables.tf
test/setup/iam.tf
test/setup/main.tf
test/setup/outputs.tf

Add support for autokey in Postgres module.
For testing its using same project as autokey project for simplicity.

feat: Add support for autokey in postgres module

---

modules/mssql/README.md
modules/mssql/main.tf
modules/mssql/variables.tf
modules/mysql/README.md
modules/mysql/main.tf
modules/mysql/metadata.display.yaml
modules/mysql/metadata.yaml
modules/mysql/variables.tf
modules/postgresql/README.md
modules/postgresql/main.tf
modules/postgresql/metadata.display.yaml
modules/postgresql/metadata.yaml
modules/postgresql/variables.tf

PR adds:
- Add `enable_dataplex_integration` setting for `mssql`, `mysql` and `postgresql` database modules. instance.https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#enable_dataplex_integration-1 
Official Cloudsql <-> Dataplex integration docs https://cloud.google.com/sql/docs/postgres/dataplex-catalog-integration

feat: add setting enable_dataplex_integration

---

modules/postgresql/read_replica.tf

The `psc_config` dynamic block in resource `google_sql_database_instance.replicas` keeps getting removed by the planner while the defaults are always present. 
This pull request keeps the block with default values when PSC is disabled inside the replica.
No functional changes. Keeps the plan tidy, that's all

Fix: Postgres read-replica "psc_enabled" change never set

---

modules/mssql/main.tf
modules/mysql/main.tf
modules/postgresql/main.tf

When var.data_cache_enabled is set to false, the dynamic block data_cache_config is ignored. Exemple with [mysql module](https://github.com/terraform-google-modules/terraform-google-sql-db/blob/main/modules/mysql/main.tf#L107):
```
for_each = var.edition == "ENTERPRISE_PLUS" && var.data_cache_enabled ? ["cache_enabled"] : []
```
Due to this, the default value on GCP Cloud SQL, which is `true`, is applied.
Example:
- Create Cloud SQL instance:
```
gcloud sql instances create mysql-testing-instance --region europe-west1 --tier 'db-perf-optimized-N-2' --project-id sbx --database-version 'MYSQL_8_0' --edition ENTERPRISE_PLUS
```
- Check the data cache value:
```
gcloud sql instances describe mysql-testing-instance --project sbx | grep -A 2 dataCacheConfig
dataCacheConfig:
dataCacheEnabled: …
```

fix: Disable SQL instance data_cache when data_cache_enabled variable is false

---

modules/backup/main.tf

Fixes https://github.com/terraform-google-modules/terraform-google-sql-db/issues/733
My database name is 35 characters long. The `Managed by Terraform - Service account for backup of SQL Instance ` string is 66 characters long. In total this makes 101 characters, which fails the validation check to create the service account:
```
Error: Error creating service account: googleapi: Error 400: The display_name length (101) is longer than the maximum allowed length 100., badRequest
with module.cloudsql_backup[0].google_service_account.sql_backup_serviceaccount[0],
on .terraform/modules/cloudsql_backup/modules/backup/main.tf line 33, in resource "google_service_account" "sql_backup_serviceaccount":
33: resource "google_service_account" "sql_backup_serviceaccount" {
```
This change will truncate …

fix: truncate service account display_name in backup module

---

modules/postgresql/read_replica.tf

PR #718 was a temporary [workaround](https://github.com/terraform-google-modules/terraform-google-sql-db/pull/718#issuecomment-2789662923) for a provider bug, but now causes **permanent drift**:
```hcl
+ psc_config {
+ allowed_consumer_projects = []
+ psc_enabled               = false
}
```
**Root cause:** Workaround forces `psc_config` creation via `["psc_disabled"]`, but GCP API omits the block when PSC is disabled → constant state mismatch.
The original provider issue is fixed, reverting to the original behavior:
```diff
- for_each = ip_configuration.value.psc_enabled ? ["psc_enabled"] : ["psc_disabled"]
+ for_each = lookup(ip_configuration.value, "psc_enabled", false) ? [1] : []
```
✅ `psc_enabled = false` → No drift, no unnecessary blocks
✅ `psc_enabled = true` → Proper block …

fix: revert psc_config workaround - causes permanent drift

---

Makefile
metadata.yaml
modules/backup/metadata.yaml
modules/mssql/metadata.yaml
modules/mysql/metadata.yaml
modules/postgresql/metadata.yaml
modules/private_service_access/metadata.yaml
modules/restore/metadata.yaml
modules/safer_mysql/metadata.yaml
test/setup/iam.tf
test/setup/main.tf

Introduced:
- per_module_roles: to config required roles to run each sub modules.
- per_module_service: to config required services to run each sub modules.
Added feature flag `--per-module-requirements` to generate_docs cmd, to align with the per module configs.

feat: per module requirements
