terraform-google-modules/terraform-google-sql-db

CONTRIBUTING.md

Hi
I did a small change to correct links.
Thanks.

Broken markdown for links

---

main.tf
outputs.tf
variables.tf

Hi
I added some forgotten variables.
I did some tests and it was working.
Thanks !

add some forgotten variables

---

examples/mysql-and-postgres/main.tf
main.tf
outputs.tf
variables.tf

dbtags and replica support

---

outputs.tf

Fix typo in outputs instance time to retire

---

main.tf
variables.tf

Just adding availability type to module.

availability type variable

---

test/fixtures/postgresql-ha/main.tf

fix a regression for test

---

examples/mysql-and-postgres/main.tf

fix: using network's name in private-service-access module

---

modules/mysql/failover_replica.tf
modules/mysql/read_replica.tf
modules/mysql/variables.tf
modules/postgresql/read_replica.tf
modules/postgresql/variables.tf
test/fixtures/mysql-ha/main.tf
test/fixtures/postgresql-ha/main.tf
test/integration/mysql-ha/controls/mysql.rb
test/integration/postgresql-ha/controls/pg.rb

Fixes #49
@wadefrancis @morgante could you review this?

make each ip_configuration pass properly to replicas

---

CHANGELOG.md
README.md
docs/upgrading_to_sql_db_3.0.0.md

Add upgrade guide for 3.0. Update readme.

---

README.md

Fixed the source path to mysql and posgresql modules in the examples.

Fix source path for examples

---

modules/mssql/README.md
modules/mssql/main.tf
modules/mssql/variables.tf

In addition to `for_each`, I've removed extra labels by using module dependency.
I'm sorry I didn't notice it in the review.
cc @morgante

use for_each instead of count, fixes #113

---

modules/mssql/README.md
modules/mssql/main.tf
modules/mssql/variables.tf

This adds backup configuration settings to MSSQL module. Reference #128 .

backup_configuration for mssql database type

---

README.md

Workaround for https://github.com/hashicorp/terraform/issues/21452

chore(docs): Update relative links

---

modules/safer_mysql/README.md
modules/safer_mysql/main.tf
modules/safer_mysql/variables.tf

add encryption_key_name var to safer_mysql module

add encryption_key_name to safer_mysql module

---

modules/safer_mysql/variables.tf

PR https://github.com/terraform-google-modules/terraform-google-sql-db/pull/185 added trailing whitespace which is breaking builds

lint to fix build

---

modules/postgresql/README.md
modules/postgresql/main.tf
modules/postgresql/variables.tf

For #188 since provider already supporting insights config (https://github.com/hashicorp/terraform-provider-google/pull/8434).

Support Query Insights

---

modules/mysql/outputs.tf
modules/postgresql/outputs.tf

Addresses https://github.com/terraform-google-modules/terraform-google-sql-db/issues/192

remove empty string from replicas output lists

---

examples/mysql-ha/README.md
examples/mysql-ha/outputs.tf
examples/postgresql-ha/README.md
examples/postgresql-ha/outputs.tf
modules/mssql/README.md
modules/mssql/outputs.tf
modules/mysql/README.md
modules/mysql/outputs.tf
modules/postgresql/README.md
modules/postgresql/outputs.tf
modules/safer_mysql/README.md
modules/safer_mysql/outputs.tf
test/fixtures/mysql-ha/outputs.tf
test/fixtures/postgresql-ha/outputs.tf
test/integration/mysql-ha/controls/mysql.rb
test/integration/mysql-ha/inspec.yml
test/integration/postgresql-ha/controls/pg.rb
test/integration/postgresql-ha/inspec.yml

Addresses part of https://github.com/terraform-google-modules/terraform-google-sql-db/issues/192

Add outputs for the actual `google_sql_database_instance` resources

---

build/int.cloudbuild.yaml
kitchen.yml

This addresses [this](https://github.com/terraform-google-modules/terraform-google-sql-db/issues/243) issue.
Fixes #254

chore:adds back the postgresql-public-iam int test

---

README.md

Readme had outdated versions. That caused me to try out some very old versions in my terraform setup.

update version examples in readme

---

modules/postgresql/outputs.tf

Running a terraform plan using the postgresql module resulted in two errors for these outputs. I believe this is the expected fix

Add sensitive flag for two outputs

---

docs/upgrading_to_sql_db_11.0.0.md
modules/mysql/main.tf
modules/mysql/outputs.tf
modules/postgresql/main.tf
modules/postgresql/outputs.tf

https://github.com/terraform-google-modules/terraform-google-sql-db/pull/297 with upgrade guidance

feat!: Switch to random_password instead of random_id

---

README.md
modules/mssql/README.md

I have fixed Issue #298 with this PR.

chore: update READMEs

---

modules/restore/README.md
modules/restore/main.tf
modules/restore/outputs.tf
modules/restore/templates/import.yaml.tftpl
modules/restore/variables.tf
modules/restore/versions.tf

The restore module is using Cloud SQL Import API call through a Workflow. This module is an extension of backup module's export function.

Added cloud sql restore module that uses database import

---

modules/mssql/main.tf
modules/mssql/outputs.tf
modules/mysql/main.tf
modules/mysql/outputs.tf
modules/postgresql/main.tf
modules/postgresql/outputs.tf

fix: disable random_pass when default user off

---

modules/backup/README.md

chore: Fix typo in backup module readme

---

Makefile
modules/postgresql/metadata.yaml

This PR adds connections metadata for postgresql module

chore: Add connections metadata

---

modules/postgresql/metadata.yaml

Remove duplicate connections property

chore: Fix connection metadata

---

modules/mysql/metadata.yaml
modules/postgresql/metadata.yaml

Update connection source version to comply with semantic versioning

chore: Update connection metadata
